/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.uagro.miidt.preeclamsia.app;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import weka.classifiers.lazy.IBk;
import weka.classifiers.trees.J48;
import weka.classifiers.trees.RandomForest;
import weka.core.Attribute;
import weka.core.DenseInstance;
import weka.core.Instance;
import weka.core.Instances;
import weka.core.SerializationHelper;

/**
 *
 * @author RabDos
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextEdad = new javax.swing.JTextField();
        jTextIMCMat = new javax.swing.JTextField();
        jTextTAS = new javax.swing.JTextField();
        jTextTotGestas = new javax.swing.JTextField();
        jTextVpm = new javax.swing.JTextField();
        jTextNeutrofilo = new javax.swing.JTextField();
        jTextEosinofilo = new javax.swing.JTextField();
        jButtonPred = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelRForest = new javax.swing.JLabel();
        jLabelIBk = new javax.swing.JLabel();
        jLabelJ48 = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Preeclampsia MIIDT");

        jLabel2.setText("Edad");

        jLabel3.setText("IMCMat");

        jLabel4.setText("TAS");

        jLabel5.setText("Total de Gestas");

        jLabel6.setText("VPM");

        jLabel7.setText("Neutrófilo");

        jLabel8.setText("Eosinófilo");

        jTextEdad.setToolTipText("");
        jTextEdad.setName("jTextEdad"); // NOI18N
        jTextEdad.setPreferredSize(new java.awt.Dimension(50, 22));
        jTextEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEdadActionPerformed(evt);
            }
        });

        jTextIMCMat.setName("jTextIMCMat"); // NOI18N
        jTextIMCMat.setPreferredSize(new java.awt.Dimension(50, 22));

        jTextTAS.setName("jTextTAS"); // NOI18N
        jTextTAS.setPreferredSize(new java.awt.Dimension(50, 22));

        jTextTotGestas.setName("jTextTotGestas"); // NOI18N
        jTextTotGestas.setPreferredSize(new java.awt.Dimension(50, 22));

        jTextVpm.setName("jTextVpm"); // NOI18N
        jTextVpm.setPreferredSize(new java.awt.Dimension(50, 22));
        jTextVpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVpmActionPerformed(evt);
            }
        });

        jTextNeutrofilo.setName("jTextNeutrofilo"); // NOI18N
        jTextNeutrofilo.setPreferredSize(new java.awt.Dimension(50, 22));

        jTextEosinofilo.setName("jTextEosinofilo"); // NOI18N
        jTextEosinofilo.setPreferredSize(new java.awt.Dimension(50, 22));
        jTextEosinofilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEosinofiloActionPerformed(evt);
            }
        });

        jButtonPred.setText("Predicción");
        jButtonPred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredActionPerformed(evt);
            }
        });

        jLabel9.setText("RandomForest:");

        jLabel10.setText("IBk:");

        jLabel11.setText("J48:");

        jLabelRForest.setText("-----");

        jLabelIBk.setText("-----");

        jLabelJ48.setText("-----");

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(79, 79, 79)
                                .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64)
                                .addComponent(jTextIMCMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(83, 83, 83)
                                .addComponent(jTextTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextTotGestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPred, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextEosinofilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextNeutrofilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextVpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jButtonLimpiar))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRForest)
                            .addComponent(jLabelIBk)
                            .addComponent(jLabelJ48))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelRForest))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jTextIMCMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNeutrofilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelIBk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jTextTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEosinofilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelJ48))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPred)
                        .addComponent(jButtonLimpiar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextTotGestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabelTitle");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextVpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVpmActionPerformed

    private void jButtonPredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredActionPerformed
        // TODO add your handling code here:
        
        if(jTextEdad.getText().length()<=0){
        JOptionPane.showMessageDialog(null, "Por favor ingrese la edad", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else if (jTextIMCMat.getText().length()<=0){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el valor "
                    + "de ICMat", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else if (jTextTAS.getText().length()<=0){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el valor "
                    + "de TAS", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else if(jTextTotGestas.getText().length()<=0){
        JOptionPane.showMessageDialog(null, "Por favor ingrese el valor del "
                + "total de gestas", "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
        }else if(jTextVpm.getText().length()<=0){
        JOptionPane.showMessageDialog(null, "Por favor ingrese el valor de VPM", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else if(jTextNeutrofilo.getText().length()<=0){
        JOptionPane.showMessageDialog(null, "Por favor ingrese el valor de "
                + "Neutrófilo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else if(jTextEosinofilo.getText().length()<=0){
        JOptionPane.showMessageDialog(null, "Por favor ingrese el valor de "
                + "Eosinófilo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        try {
            RandomForest rForest = (RandomForest)SerializationHelper.read("src/"
                    + "assets/RandomForest.model");
            IBk iBk = (IBk)SerializationHelper.read("src/"
                    + "assets/IBk.model");
            J48 j48 = (J48)SerializationHelper.read("src/"
                    + "assets/J48.model");
            
//            Attribute edad = new Attribute("edad"); 
//            Attribute IMCMat = new Attribute("IMCMat"); 
//            Attribute TAS = new Attribute("TAS"); 
//            Attribute totGestas = new Attribute("totGestas"); 
//            Attribute vpm = new Attribute("vpm"); 
//            Attribute neutrofilo = new Attribute("neutrofilo"); 
//            Attribute eosinofilo  = new Attribute("eosinofilo "); 
            
            ArrayList <Attribute> attributes = new ArrayList<>();
            ArrayList <String> classes = new ArrayList<>();
            attributes.add(new Attribute("edad"));
            attributes.add(new Attribute("IMCMat"));
            attributes.add(new Attribute("TAS"));
            attributes.add(new Attribute("totGestas"));
            attributes.add(new Attribute("vpm"));
            attributes.add(new Attribute("neutrofilo"));
            attributes.add(new Attribute("eosinofilo "));
            classes.add("1");
            classes.add("0");
            attributes.add(new Attribute("prediccion",classes));
            
            Instances data = new Instances("MIIDTWEKA-Preeclampsia-weka."
                    + "filters.unsupervised.attribute.Remove-R2-9,12,14-24,26,"
                    + "28-29,31-38",attributes,0);
            double instance [] = new double[data.numAttributes()];
            instance[0] = Double.parseDouble(jTextEdad.getText());
            instance[1] = Double.parseDouble(jTextIMCMat.getText());
            instance[2] = Double.parseDouble(jTextTAS.getText());
            instance[3] = Double.parseDouble(jTextTotGestas.getText());
            instance[4] = Double.parseDouble(jTextVpm.getText());
            instance[5] = Double.parseDouble(jTextNeutrofilo.getText());
            instance[6] = Double.parseDouble(jTextEosinofilo.getText());
            
            data.add(new DenseInstance(1.0,instance));
            data.setClassIndex(data.numAttributes()-1);
            Instance inst = data.instance(0);
            System.out.println("instancia "+inst.toString());
            double predRForest = rForest.classifyInstance(inst);
            double predIbk = iBk.classifyInstance(inst);
            double predJ48 = j48.classifyInstance(inst);
            
            jLabelRForest.setText((predRForest == 0.0)? "clase 1":"clase 0");
            jLabelIBk.setText((predIbk == 0.0)?"clase 1":"clase 0");
            jLabelJ48.setText((predJ48 == 0.0)?"clase 1":"clase 0");
            
        } catch (Exception ex) {
            System.err.println(ex);
        }
        
        
    }//GEN-LAST:event_jButtonPredActionPerformed

    private void jTextEosinofiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEosinofiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEosinofiloActionPerformed

    private void jTextEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEdadActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextEdad.setText(null);
        jTextIMCMat.setText(null);
        jTextTAS.setText(null);
        jTextTotGestas.setText(null);
        jTextVpm.setText(null);
        jTextNeutrofilo.setText(null);
        jTextEosinofilo.setText(null);
        jLabelRForest.setText("-----");
        jLabelIBk.setText("-----");
        jLabelJ48.setText("-----");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonPred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIBk;
    private javax.swing.JLabel jLabelJ48;
    private javax.swing.JLabel jLabelRForest;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextEosinofilo;
    private javax.swing.JTextField jTextIMCMat;
    private javax.swing.JTextField jTextNeutrofilo;
    private javax.swing.JTextField jTextTAS;
    private javax.swing.JTextField jTextTotGestas;
    private javax.swing.JTextField jTextVpm;
    // End of variables declaration//GEN-END:variables
}
